### PR TITLE
assignment_submission_Furkan_Guner

### PR DESCRIPTION
**Pull request by furkangnr**
test rmse: 30366.1662
test r2: 0.8658

### CODE REVIEW

**Comment by solegalli** [comment]
Hi @furkangnr 

Well done on beating my model. 

I can't unfortunately merge this PR because there are 7 files changed. There should only be 1 file added, your solution to the problem, within the StudentsSolutions Folder.

Could you either remove unwanted files or make a new PR with just your solution?

Thank you!

**Comment by furkangnr** [comment]
Hi @solegalli ,

I deleted unnecessary files and committed to the master branch. Could you please review my commits and give me a feedback. If it is not a proper pull request, I will try to open a new one. 

Thanks.

**Comment by solegalli** [comment]
It looks like this PR, the way it stands now will delete most main files and add yours. So I can't merge it unfortunately.

At the top of the PR, on the tab "files changed" we should see only 1 file, your solution inside the students solutions folder.

It would be great if you could, 

- check out master from this repo in a separate branch (not your master, which is probably out of sync)
- add your solution to this new branch (StudentsSolutions_v1.0.0/13-Assignement_FurkanGuner.ipynb )
- make a PR from this branch.

Alternatively, try to re-sync your master with this repo's master. Then create a new branch from there. Add the solution and make a new PR.

In either case, make a copy of your solution so you don't lose it just in case.

Cheers
Sole

**Comment by furkangnr** [comment]
Hi @solegalli,

I opened a brand new Pull Request. I hope this time it will be okay :) Thank you for your attention and patience.

I posted on Linkedin about this course and tagged you, it would be great if you can add a comment etc. in order to enrich the post. 
My Linkedin profile is : 
https://www.linkedin.com/in/furkan-güner-453a06124/

I will close this PR after you see and accept my brand new PR.

Have a nice day !

**Comment by solegalli** [comment]
@furkangnr thanks a lot for making the new PR!

Enjoy your day

**Pull request closed without merging**
