### PR TITLE
test rmse: 29749, test r2: 0.871

### PR DESCRIPTION
**Pull request by FlorianMeierITUC**
Hi Soledad,
just finished working on the final assignment and would like to ask you to fulfill my pull request :)

Best, Flo

### CODE REVIEW

**Comment by solegalli** [comment]
Hi @FlorianMeierITUC 

Well done on finishing the course.

In the pipeline, I notice that you are scaling the data twice: once with the RobustScaler and then with the MinMaxScaler. Is this intentional? It is a very unusual procedure, that's why I ask.

Cheers
Sole

**Comment by FlorianMeierITUC** [comment]
Hi Sole,
actually this was not intentional :D Took the approach of permuting the "ingedrients" and kinda forgot to comment the second scaler. Not very surprisingly commenting out the RobustScaler does not change the result. 

Best
Flo

**Comment by solegalli** [comment]
Great, thank you! Could you then please either remove it or comment it out before I merge?

**Comment by FlorianMeierITUC** [comment]
Just cleaned up the pipeline and pushed a new commit.

Best, Flo

**Comment by solegalli** [comment]
Hi @FlorianMeierITUC 

Sorry it took me so long to reply. There is an additional file in this PR that needs to be removed. 

By the looks of it we are adding 13-Assignement_FlorianMeier.ipynb both within and outside the students assignment folder. 

We should add it only inside the folder.

Thank you!

**Comment by FlorianMeierITUC** [comment]
Hi Sole,
this course turns out to become a lesson on git for me :D
I deleted the file outside the students assignment folder. Hopefully by removing this file I did not mess up the folder structure.

Best, Flo

**Comment by solegalli** [comment]
Excellent! Thank you!

I hope working with git was not too frustrating. I found it so hard at the beginning :_(

Thanks a lot for your engagement!

**Pull request merged**
