### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jacopobozzi86**
Jacopo Bozzi Solution

### CODE REVIEW

**Comment by jacopobozzi86** [comment]
Hi Soledad, this is the pull request for my solution

**Comment by solegalli** [comment]
Hi @jacopobozzi86 

I can see that you changed a few transformations and that improved the performance. Well done.

The RareLabelEncoder does not seem to be working on the selected variables though. Most variables have less than 6 categories and therefore are not grouped.

Did you try removing that step and seeing how the performance changes?

**Comment by jacopobozzi86** [comment]
Hi Soledad,

yes I will try to do it tonight and I will do another pull request.
Thanks a lot for the feedback.

Jacopo

**Comment by jacopobozzi86** [comment]
Hi @solegalli 

last night I pulled my new solution.
Here the results:

test mse: 918253390.4498676
test rmse: 30302.696092094968
test r2: 0.8663798041581581

**Comment by solegalli** [comment]
Hi @jacopobozzi86 

Sorry for the delayed response. I was on holidays.

The notebook seems to contain the old pipeline, which is now returning an error upon execution. Would you mind fixing that?

thank you!

**Comment by jacopobozzi86** [comment]
Hi @solegalli,

I corrected the code and it should work now.

I changed the rare labes enconding in this way:

 # categorical encoding - section 6
    ('rare_label_enc',
     ce.RareLabelEncoder(tol=0.005, n_categories=1, variables=categorical + discrete)),

it gives me the results mentioned above.

Regards
Jacopo

**Pull request merged**
